version: '3.1'
services:
  app:
    container_name: prophius-assessment
    image: prophius-assessment
    build:
      context: .                          #docker file path (. means root directory)
      dockerfile: Dockerfile              #docker file name
    ports:
      - 9999:9999
    restart: always
    network_mode: host
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/backend
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_PROPERTIES_HIBERNATE_FORMAT_SQL=true
